import { Inter } from "next/font/google";
import "./globals.css";

import { cookies } from "next/headers";
import LayoutWrapper from "@/components/LayoutWrapper";

const inter = Inter({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter"
})
export const metadata = {
  title: "Bangladesh Now",
  description: "Generated by create next app",
};







export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <LayoutWrapper>
          {children}
        </LayoutWrapper>

      </body>
    </html>
  );
}
